// Euler_Fibonacci_2.cpp : Defines the entry point for the console application.
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <SDKDDKVer.h>
#include <iostream>
using namespace std;

__forceinline bool iseven(long i)
{
	return ( 0 == (i % 2) );
}

int main(int argc, char* argv[])
{
	long sum = 0;
	long prev = 1;
	long fib = 1;
	long temp = 1;

	while (fib <= 400000)
	{
		if (iseven(fib))
		{
			sum += fib;
		}

		temp = fib;
		fib += prev;
		prev = temp;
	}

	cout << endl << "Sum: " << sum << endl;
	cin.ignore();

	return 0;
}
